### ISSUE TITLE
Add Scripture version choice to scripture settings

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/single-scripture-rcl#6]
Add a dropdown for 4 previously used scripture versions and a textbox for entering a URL of a scripture repo like tC-Create 1.0
 ex: https://git.door43.org/ru_gl/ru_rsob

If the book doesn't exist in that repository the card should display what tC displays when a resource doesn't have the book. 

another example to add: https://git.door43.org/Door43-Catalog/hi_glt

**Comment by PhotoNomad0** [comment]
Notes:
- In 1.0 the icon to select versions looks like (circled): 

![Screen Shot 2021-01-19 at 11 32 59 AM](https://user-images.githubusercontent.com/14238574/105064724-18cbf980-5a4b-11eb-977d-eb1ccf976a9a.png)

- the popup looks like:

![Screen Shot 2021-01-19 at 11 32 46 AM](https://user-images.githubusercontent.com/14238574/105064874-4153f380-5a4b-11eb-9d5f-31d878b7b853.png)

**Comment by birchamp** [comment]
@PhotoNomad0 let's add the dropdown to the scripture settings. 
![image](https://user-images.githubusercontent.com/10272744/105066609-f804a380-5a4c-11eb-855d-3a6a65144707.png)

**Comment by PhotoNomad0** [comment]
Notes:

Still to do:
- [ ] ability to delete resources from history.
- [ ] add version to title for drop down.
- [ ] add hover for license with click to navigate to license on 
- [ ] how create handles invalid URLs - it does not add it to list, but no error message:

<img width="564" alt="Screen Shot 2021-01-25 at 4 17 15 PM" src="https://user-images.githubusercontent.com/14238574/105768919-0fe79600-5f2b-11eb-9a5b-63d18091857b.png">

**Comment by PhotoNomad0** [comment]
@birchamp I added notes above about how tc-create 1.0 handles.  Would like feedback about which features we still need to add at this time.

**Comment by PhotoNomad0** [comment]
@birchamp -  OK found an example of how to add components to drop down list...

**Comment by PhotoNomad0** [comment]
@birchamp Does this look sufficient for this next release? 
<img width="544" alt="Screen Shot 2021-01-26 at 3 01 33 PM" src="https://user-images.githubusercontent.com/14238574/105898439-6c0ff000-5fe7-11eb-9162-b729009eb4b7.png">
